name: Video_content_generation

on:
  schedule:
    # Run daily at 12:00 UTC
    - cron: '0 12 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to run the workflow'
        required: true
        default: 'main'
      prompt_index:
        description: 'Override the prompt index (leave empty to use chronological order)'
        required: true
        type: string

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install ffmpeg for video processing
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Load prompt based on date
        id: get-prompt
        run: |
          # Calculate which day of the year it is (for chronological ordering)
          if [ -z "${{ github.event.inputs.prompt_index }}" ]; then
            DAY_OF_YEAR=$(date +%j)
            echo "Using day of year: $DAY_OF_YEAR"
            echo "PROMPT_INDEX=$DAY_OF_YEAR" >> $GITHUB_ENV
          else
            echo "Using manual index: ${{ github.event.inputs.prompt_index }}"
            echo "PROMPT_INDEX=${{ github.event.inputs.prompt_index }}" >> $GITHUB_ENV
          fi
      
      - name: Generate content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
        run: |
          python ../../src/video_content_creator/main_orchestration.py --from-prompt-file ../../data/prompts.json --prompt-index ${{ env.PROMPT_INDEX }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-content
          path: output/
          retention-days: 2
